### ISSUE TITLE
arm-none-eabi-as: command not found

### ISSUE THREAD

**Issue by arteze** [pret/agbcc#42] opened 2021-06-23 03:19 UTC
Failure `./build.sh`:

```sh
make: Entering directory '/agbcc/agbcc/libgcc'
rm -f tmplibgcc1.a
set -e
for name in _udivsi3 _divsi3 _umodsi3 _modsi3 _dvmd_tls _call_via_rX; \
do \
  echo ${name}; \
  cc -E -undef -nostdinc -DL${name} -x assembler-with-cpp -o ${name}.s lib1thumb.asm; \
  bash -c 'echo -e ".text\n\t.align\t2, 0\n"' >> ${name}.s ; \
  arm-none-eabi-as -mcpu=arm7tdmi -o ${name}.o ${name}.s; \
  rm -f ${name}.s; \
  arm-none-eabi-ar -rc tmplibgcc1.a ${name}.o; \
  rm -f ${name}.o; \
done
_udivsi3
/bin/sh: line 5: arm-none-eabi-as: command not found
/bin/sh: line 7: arm-none-eabi-ar: command not found
_divsi3
/bin/sh: line 5: arm-none-eabi-as: command not found
/bin/sh: line 7: arm-none-eabi-ar: command not found
_umodsi3
/bin/sh: line 5: arm-none-eabi-as: command not found
/bin/sh: line 7: arm-none-eabi-ar: command not found
_modsi3
/bin/sh: line 5: arm-none-eabi-as: command not found
/bin/sh: line 7: arm-none-eabi-ar: command not found
_dvmd_tls
/bin/sh: line 5: arm-none-eabi-as: command not found
/bin/sh: line 7: arm-none-eabi-ar: command not found
_call_via_rX
/bin/sh: line 5: arm-none-eabi-as: command not found
/bin/sh: line 7: arm-none-eabi-ar: command not found
mv tmplibgcc1.a libgcc1.a
mv: cannot stat 'tmplibgcc1.a': No such file or directory
make: *** [Makefile:36: libgcc1.a] Error 1
make: Leaving directory '/agbcc/agbcc/libgcc'
```

**Comment by PikalaxALT** [comment] 2021-06-24 12:23
Hi, did you install devkitARM and define the environment variables as per the instructions in the GBA project you're trying to build?

**Comment by arteze** [comment] 2021-06-24 19:32
I could not install it because there was a problem in the packet subdomain:

- https://pkg.devkitpro.org

`File not found`

But I just got research and I already installed `binutils-arm-none-eabi`.

```sh
arm-none-eabi-ar -rc libc.a ./stdio/fwrite.o ./stdio/wsetup.o ./stdio/fgets.o ./stdio/setbuf.o ./stdio/fwalk.o ./stdio/fread.o ./stdio/fiprintf.o ./stdio/vprintf.o ./stdio/puts.o ./stdio/refill.o ./stdio/perror.o ./stdio/fputs.o ./stdio/vfscanf.o ./stdio/fflush.o ./stdio/fputc.o ./stdio/fgetpos.o ./stdio/fsetpos.o ./stdio/fdopen.o ./stdio/rewind.o ./stdio/getc.o ./stdio/iprintf.o ./stdio/makebuf.o ./stdio/fopen.o ./stdio/fvwrite.o ./stdio/setvbuf.o ./stdio/mktemp.o ./stdio/putchar.o ./stdio/stdio.o ./stdio/fscanf.o ./stdio/ferror.o ./stdio/fgetc.o ./stdio/sscanf.o ./stdio/clearerr.o ./stdio/ftell.o ./stdio/rget.o ./stdio/printf.o ./stdio/fclose.o ./stdio/sprintf.o ./stdio/gets.o ./stdio/flags.o ./stdio/tmpfile.o ./stdio/ungetc.o ./stdio/freopen.o ./stdio/fseek.o ./stdio/putc.o ./stdio/scanf.o ./stdio/vsprintf.o ./stdio/getchar.o ./stdio/findfp.o ./stdio/fileno.o ./stdio/fprintf.o ./stdio/remove.o ./stdio/tmpnam.o ./stdio/rename.o ./stdio/siprintf.o ./stdio/wbuf.o ./stdio/vfprintf.o ./stdio/feof.o ./locale/locale.o ./time/ctime_r.o ./time/lcltime.o ./time/asctime.o ./time/asctime_r.o ./time/difftime.o ./time/mktime.o ./time/ctime.o ./time/gmtime_r.o ./time/time.o ./time/clock.o ./time/strftime.o ./time/lcltime_r.o ./time/gmtime.o ./reent/signalr.o ./reent/fstatr.o ./reent/lseekr.o ./reent/impure.o ./reent/linkr.o ./reent/writer.o ./reent/readr.o ./reent/closer.o ./reent/sbrkr.o ./reent/execr.o ./reent/timer.o ./reent/reent.o ./reent/openr.o ./reent/statr.o ./arm/syscalls.o ./arm/libcfunc.o ./syscalls/sysread.o ./syscalls/systimes.o ./syscalls/sysstat.o ./syscalls/sysfcntl.o ./syscalls/sysfstat.o ./syscalls/syskill.o ./syscalls/sysexecve.o ./syscalls/sysgettod.o ./syscalls/syslink.o ./syscalls/sysfork.o ./syscalls/sysopen.o ./syscalls/sysclose.o ./syscalls/syswait.o ./syscalls/syswrite.o ./syscalls/sysunlink.o ./syscalls/syslseek.o ./syscalls/sysgetpid.o ./syscalls/syssbrk.o ./math/s_infconst.o ./math/s_finite.o ./math/sf_scalbn.o ./math/sf_modf.o ./math/s_isinf.o ./math/s_frexp.o ./math/s_scalbn.o ./math/s_ldexp.o ./math/sf_finite.o ./math/s_copysign.o ./math/sf_ldexp.o ./math/s_isnan.o ./math/s_modf.o ./math/sf_copysign.o ./math/sf_isinf.o ./math/sf_frexp.o ./math/sf_isnan.o ./string/strstr.o ./string/strlwr.o ./string/strcat.o ./string/strtok_r.o ./string/strncasecmp.o ./string/memcpy.o ./string/u_strerr.o ./string/strncpy.o ./string/strcoll.o ./string/memcmp.o ./string/bcopy.o ./string/strcspn.o ./string/strncat.o ./string/memset.o ./string/index.o ./string/strncmp.o ./string/strxfrm.o ./string/strchr.o ./string/strtok.o ./string/memmove.o ./string/strspn.o ./string/strcasecmp.o ./string/strpbrk.o ./string/strerror.o ./string/strcpy.o ./string/strupr.o ./string/strcmp.o ./string/strlen.o ./string/strrchr.o ./string/bzero.o ./string/memchr.o ./string/bcmp.o ./string/rindex.o ./errno/errno.o ./misc/dprintf.o ./misc/unctrl.o ./misc/ffs.o ./ctype/ispunct.o ./ctype/isalpha.o ./ctype/toascii.o ./ctype/_tolower.o ./ctype/isdigit.o ./ctype/tolower.o ./ctype/isspace.o ./ctype/_toupper.o ./ctype/isascii.o ./ctype/ctype_.o ./ctype/isprint.o ./ctype/isalnum.o ./ctype/isxdigit.o ./ctype/toupper.o ./ctype/islower.o ./ctype/iscntrl.o ./ctype/isupper.o ./signal/raise.o ./signal/signal.o ./stdlib/mbstowcs_r.o ./stdlib/efgcvt.o ./stdlib/qsort.o ./stdlib/strdup.o ./stdlib/ldiv.o ./stdlib/labs.o ./stdlib/abs.o ./stdlib/mbtowc_r.o ./stdlib/mbtowc.o ./stdlib/environ.o ./stdlib/wctomb.o ./stdlib/msize.o ./stdlib/getopt.o ./stdlib/assert.o ./stdlib/atexit.o ./stdlib/malign.o ./stdlib/atof.o ./stdlib/atoff.o ./stdlib/rand_r.o ./stdlib/system.o ./stdlib/mbstowcs.o ./stdlib/ecvtbuf.o ./stdlib/dtoa.o ./stdlib/calloc.o ./stdlib/exit.o ./stdlib/bsearch.o ./stdlib/dtoastub.o ./stdlib/__exp10.o ./stdlib/rand.o ./stdlib/wcstombs.o ./stdlib/setenv.o ./stdlib/strtoul.o ./stdlib/eprintf.o ./stdlib/__adjust.o ./stdlib/putenv.o ./stdlib/mlock.o ./stdlib/realloc.o ./stdlib/div.o ./stdlib/strtod.o ./stdlib/mstats.o ./stdlib/valloc.o ./stdlib/mtrim.o ./stdlib/mblen.o ./stdlib/abort.o ./stdlib/mprec.o ./stdlib/malloc.o ./stdlib/atoi.o ./stdlib/strtol.o ./stdlib/wcstombs_r.o ./stdlib/getenv.o ./stdlib/__ten_mu.o ./stdlib/atol.o ./stdlib/wctomb_r.o stdlib/mallocr.o stdlib/freer.o stdlib/reallocr.o stdlib/callocr.o stdlib/cfreer.o stdlib/malignr.o stdlib/vallocr.o stdlib/pvallocr.o stdlib/mallinfor.o stdlib/mallstatsr.o stdlib/msizer.o stdlib/malloptr.o stdio/vfiprintf.o arm/setjmp.o arm/trap.o
make: Leaving directory '/agbcc/libc'
```

With that the problem is solved, it was able to compile correctly.

**Comment by PikalaxALT** [comment] 2021-06-24 19:42
Glad to hear! If the problem is resolved, please close this issue.

**Comment by arteze** [comment] 2021-06-24 20:10
I have a bug in the browser that does not allow me to close it.

**Closed as completed** 2021-06-24 20:28 UTC
